[package]
name = "bevy_rs"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy_ecs = "0.13"
clap = { version = "4.5.9", features = ["derive"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
